### PR TITLE
Bump AGP to 8.5.1

### PR DESCRIPTION
**Pull request by wzieba**

### CODE REVIEW

**Comment by wzieba** [comment]
hi @ParaskP7 , I forgot to make this PR ready for review. The actual code was already tested in https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/3065 - can I get an approval here? 🙏

**Review by ParaskP7 — COMMENTED** [review]
👋 @wzieba !

I did a quick review of this change and below are few things I found, I hope this helps:

1. Running `./gradlew wrapper --gradle-version=8.9 --distribution-type=all --gradle-distribution-sha256-sum=258e722ec21e955201e31447b0aed14201765a3bfbae296a46cf60b70e66db70` produced a slight change for me, see: [android-dependency-catalog-33_Bump_AGP_to_8_5_1.patch](https://github.com/user-attachments/files/16507091/android-dependency-catalog-33_Bump_AGP_to_8_5_1.patch)
2. I also run the below tasks with the following results:
    - `./gradlew build`: BUILD SUCCESSFUL
    - `./gradlew example:assembleDebug`: BUILD SUCCESSFUL
    - `./gradlew example:build`: BUILD FAILURE

<details>
    <summary>CLICK TO EXPAND</summary>

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':example:verifyReleaseResources'.
> Could not resolve all dependencies for configuration ':example:releaseRuntimeClasspath'.
   > Could not resolve com.squareup.okhttp3:okhttp-bom:4.9.2.
     Required by:
         project :example > com.automattic:Automattic-Tracks-Android:2.2.0 > io.sentry:sentry-android-okhttp:5.4.3
      > No matching variant of com.squareup.okhttp3:okhttp-bom:4.9.2 was found. The consumer was configured to find a library for use during runtime, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '8.5.1', attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - Variant 'apiElements':
              - Incompatible because this component declares a platform for use during compile-time and the consumer needed a library for use during runtime
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '8.5.1')
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'enforcedApiElements':
              - Incompatible because this component declares an enforced platform for use during compile-time and the consumer needed a library for use during runtime
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '8.5.1')
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'enforcedRuntimeElements' declares a component for use during runtime:
              - Incompatible because this component declares an enforced platform and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '8.5.1')
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'runtimeElements' declares a component for use during runtime:
              - Incompatible because this component declares a platform and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '8.5.1')
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
```

</details>

Let me know what you think of the above and then we will move forward accordingly. 🙏

**Comment by wzieba** [comment]
Thanks, this Gradle wrapper thing is really annoying. I'm pretty sure it shouldn't matter from which version of Gradle I run the update: if I update to `8.9` it should always be exactly `8.9` with all wrapper files for this specific release.

I've fixed the build and added CI verification task

**Comment by ParaskP7** [comment]
> Thanks, this Gradle wrapper thing is really annoying.

Yea, I usually run this 2 times just to be sure, then commit, then run it one more time to see if I get a diff... 😅 

> I'm pretty sure it shouldn't matter from which version of Gradle I run the update: if I update to 8.9 it should always be exactly 8.9 with all wrapper files for this specific release.

🤷 @wzieba 🤷 

> I've fixed the build and added CI verification task

Thanks for fixing the build, much appreciated! 🙇 

1. Thanks for updating `automattic-tracks`, and what's more, we don't need to test this with FluxC (the only project using ADC) as it doesn't use this dependency, which is good and bad at the same time... 🤷 We are maintaining dependencies and versions for no good reason... 😞 
2. Thanks for adding the CI `example:assembleDebug` verification task, but maybe we should also consider adding all 3 of them, or at least the `build` related ones as `assembleDebug` should be included in the parent `build` task: 🤔 
    - `build` (this task usually passes anyway)
    - `example:assembleDebug` (this task is also usually passing)
    - `example:build` (this is the problematic task that sometimes fails)

FYI: I am approving this anyway to unblock you. ✅ 

PS: Unrelated, but wanted to mention that, when running `./gradlew example:build` I am, most often than not, getting the below `robolectric` related failure, not sure if we want to "somehow" fix this too:

<details>
    <summary>BUILD FAILED</summary>

```
> Task :example:generateDebugAndroidTestLintModel FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':example:generateDebugAndroidTestLintModel'.
> Could not resolve all files for configuration ':example:debugAndroidTestRuntimeClasspath'.
   > Failed to transform nativeruntime-dist-compat-1.0.12.jar (org.robolectric:nativeruntime-dist-compat:1.0.12) to match attributes {artifactType=processed-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: /Users/petros.paraskevopoulos/.gradle/caches/modules-2/files-2.1/org.robolectric/nativeruntime-dist-compat/1.0.12/bb5ab24e0f465ae280d6f72ced8623fbd8f33fb2/nativeruntime-dist-compat-1.0.12.jar.
         > Java heap space
```

</details>

**Review by ParaskP7 — APPROVED** [review]

**Pull request merged**
