### PR TITLE
[Build] Upgrade Gradle to 8.2.1 and AGP to 8.0.2

### PR DESCRIPTION
**Pull request by ParaskP7**
Platform Request: `pdnsEh-13V-p2`
Project Thread: `paaHJt-57Z-p2`

This PR upgraded Gradle to [8.2.1](https://docs.gradle.org/8.2.1/release-notes.html) and AGP to [8.0.2](https://developer.android.com/build/releases/gradle-plugin#agp-8-0-2).

FYI: The [8.1.1](https://docs.gradle.org/8.1.1/release-notes.html) Gradle upgrades had to happen in 2 parts (3958b24f8119ee4c87a2787cba2a8ae77e4e55cb and cd98dc45a7075738d6e3680b7b4bb9d1d7f7a73b). This is because of the breaking changes that this upgrade introduces, including the `AGP` upgrade and its associated breaking changes (namespace, build option, etc).

-----

🚫 Blocked By:

- [x] `Android Gradle plugin requires Java 17 to run. You are currently using Java 11.`

<details>
    <summary>CI Failure</summary>

```
[2023-07-11T12:23:16Z] FAILURE: Build failed with an exception.
--
  | [2023-07-11T12:23:16Z]
  | [2023-07-11T12:23:16Z] * Where:
  | [2023-07-11T12:23:16Z] Build file '/var/lib/buildkite-agent/builds/ci-android-i-025c4deeaeb7a771b-1/automattic/android-dependency-catalog/example/build.gradle.kts' line: 2
  | [2023-07-11T12:23:16Z]
  | [2023-07-11T12:23:16Z] * What went wrong:
  | [2023-07-11T12:23:16Z] An exception occurred applying plugin request [id: 'com.android.library', version: '8.0.2']
  | [2023-07-11T12:23:16Z] > Failed to apply plugin 'com.android.internal.library'.
  | [2023-07-11T12:23:16Z]    > Android Gradle plugin requires Java 17 to run. You are currently using Java 11.
  | [2023-07-11T12:23:16Z]       Your current JDK is located in /usr/lib/jvm/java-11-openjdk-11.0.19.0.7-1.amzn2.0.1.x86_64
  | [2023-07-11T12:23:16Z]       You can try some of the following options:
  | [2023-07-11T12:23:16Z]        - changing the IDE settings.
  | [2023-07-11T12:23:16Z]        - changing the JAVA_HOME environment variable.
  | [2023-07-11T12:23:16Z]        - changing `org.gradle.java.home` in `gradle.properties`.
```

</details>

-----

Breaking Change List:

1. [Move package from android manifest to build files](https://github.com/Automattic/android-dependency-catalog/commit/913e877443318bd2cfb168a166da4ac573dab67e)
2. [Update kotlin to 1.6.20](https://github.com/Automattic/android-dependency-catalog/pull/20/commits/708df94debab4d085f67a9b25dd8d91683196c9f)

AGP Upgrade Assistant List:

1. [Migrate dsl properties from lint options to lint](https://github.com/Automattic/android-dependency-catalog/commit/6f532c27296f5f3776af79343d0923e71d741393)

Build Resolution List:

1. [Resolve sdk version deprecated warnings for builds](https://github.com/Automattic/android-dependency-catalog/commit/8e2d624672565376ed2447c95888648ca4dc1d58)

-----

## To test 

1. Verify that all the CI checks are successful.

## To test ([FluxC PR](TODO)):

1. Based on this [commit](TODO), verify that all the CI checks are successful.
3. Smoke test the `example` app.

-----

## Merge instructions

- [x] Mark PR as `Ready for review`.
- [x] Wait for PR to get approved.
- [x] Remove `Not ready for merge` label.
- [ ] In coordination with all the other library and client PRs, merge this PR only when every PR is ready to be merged. FYI: This is a nice to have step here, but not a necessary step per se since `android-dependency-catalog` is not part of a composite build. Actually, we might need to merge this sooner to get `FluxC` working with this newer version of the catalog.

### CODE REVIEW

**Comment by oguzkocer** [comment]
For some reason Buildkite did not pick up the builds for 86f357584b8cb178b4c34e114f40c64467e9faa9, or more likely that GitHub did not report the commit to Buildkite 🤷‍♂️ , so I manually triggered it.

**Review by oguzkocer — APPROVED** [review]

**Comment by ParaskP7** [comment]
Awesome @oguzkocer , thanks for adding JDK17 support to this repo and reviewing the changes, plus manually triggering Buildkite! 🙇 ❤️ 🚀 

FYI: I went ahead, marked this PR as `Ready for review` and removed the `Not ready for merge` label.

**Comment by ParaskP7** [comment]
FYI: I just merged this PR to get FluxC working with that newer version of the catalog, which point to those upgrades.

**Comment by ParaskP7** [comment]
👋 @oguzkocer !

Just another FYI for you that after me merging this to `trunk` and creating/pushing the new tag ([1.12.0](https://github.com/Automattic/android-dependency-catalog/releases/tag/1.12.0)), its respective [GitHub Action](https://github.com/Automattic/android-dependency-catalog/actions/runs/5623086934) failed on [generate-asset](https://github.com/Automattic/android-dependency-catalog/actions/runs/5623086934/job/15237028616) due to JDK17:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/runner/work/android-dependency-catalog/android-dependency-catalog/example/build.gradle.kts' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'com.android.library', version: '8.0.2']
> Failed to apply plugin 'com.android.internal.library'.
   > Android Gradle plugin requires Java 17 to run. You are currently using Java 11.
      Your current JDK is located in /usr/lib/jvm/temurin-11-jdk-amd64
      You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.
```

I guess we just need to update the [release.yml](https://github.com/Automattic/android-dependency-catalog/blob/trunk/.github/workflows/release.yml) and more specifically the [generate-asset](https://github.com/Automattic/android-dependency-catalog/blob/trunk/.github/workflows/release.yml#L29-L50) job to maybe add the [actions/setup-java@v3](https://github.com/actions/setup-java) action with the appropriate `17` Java version, something like:

```
      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle
```

PS: I didn't want to go make this update without first consulting with you on that.

**Comment by oguzkocer** [comment]
@ParaskP7 The GitHub action issue is addressed in #22 & #23. I also moved the `1.12.0` tag to latest `trunk` and created a release from it. Since this version was not in use anywhere, I thought moving the tag was the lesser of the evils - although maybe I still should have created a new tag instead. 🤔

**Comment by oguzkocer** [comment]
@ParaskP7 While updating FluxC, I realized that we also need to update the `publishToS3` version in the catalog. I created https://github.com/Automattic/android-dependency-catalog/pull/24 for that.

We should probably also merge the `wellsql` changes and update that in the catalog before cutting a new release. `wellsql` is not an active repository, so I think it'll be fine to merge its PR early.

**Comment by ParaskP7** [comment]
👋 @oguzkocer !

> @ParaskP7 The GitHub action issue is addressed in https://github.com/Automattic/android-dependency-catalog/pull/22 & https://github.com/Automattic/android-dependency-catalog/pull/23.

Awesome, thank you so much! 🙇 ❤️ 🚀 

> I also moved the 1.12.0 tag to latest trunk and created a release from it. Since this version was not in use anywhere, I thought moving the tag was the lesser of the evils - although maybe I still should have created a new tag instead. 🤔

👍 🤫 👍 

> @ParaskP7 While updating FluxC, I realized that we also need to update the publishToS3 version in the catalog. I created https://github.com/Automattic/android-dependency-catalog/pull/24 for that.

You're right, thanks, reviewed, approved, merged! 🙇 ❤️ 🚀 

> We should probably also merge the wellsql changes and update that in the catalog before cutting a new release.

On it! 👍 

> wellsql is not an active repository, so I think it'll be fine to merge its PR early.

I agree! 💯

**Pull request merged**
