### PR TITLE
[Deps] Update `wellsql` to 1.8.0

### PR DESCRIPTION
**Pull request by ParaskP7**
This PR updates `wellsql` to [1.8.0](https://github.com/wordpress-mobile/wellsql/releases/tag/1.8.0).

FYI: For more context on why this was done see FluxC's [#2766](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2766) PR and more so this [comment](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2766#pullrequestreview-1513558491).

-----

## To test ([FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2766)):

1. Based on this [commit](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2766/commits/f9c899d5769a1d292059c3f36a78444df5728d4e), verify that all the CI checks are successful.
2. Smoke test the `example` app.

### CODE REVIEW

**Review by oguzkocer — APPROVED** [review]
@ParaskP7 I can't test this right now, but I am approving the PR to unblock the update and I'll test the FluxC PR before it's merged.

**Comment by ParaskP7** [comment]
Thanks for approving to unblock the update @oguzkocer ! 🙇 ❤️ 🚀 

> I'll test the FluxC PR before it's merged.

👍 

-----

As per the [Releasing a new catalog version](https://github.com/Automattic/android-dependency-catalog#releasing-a-new-catalog-version), and more specification the `Create a new tag by incrementing the MINOR version in MAJOR.MINOR.PATCH format` instruction, doing that and having the [1.11.0](https://github.com/Automattic/android-dependency-catalog/releases/tag/1.11.0) tag ready, after waiting for more than 40' minutes, I am still not seeing the [Release](https://github.com/Automattic/android-dependency-catalog/actions/workflows/release.yml) action being triggered.

Am I doing something wrong here (I followed [this](https://github.com/Automattic/android-dependency-catalog/pull/10#issuecomment-1478013636))? 🤔 

-----

I am also taking this opportunity to ask whether this process can be further streamlined. 🤔 

First, let me cover what I did as part of the `Create a new tag by incrementing the MINOR version in MAJOR.MINOR.PATCH format` step:

1. First, I went to `trunk` and pulled the latest changes, after having this PR merged.
2. Then, I listed all my local tags: `git tag`
3. Then, I listed all the remote tags: `git ls-remote --tags origin`
4. Then, I fetched all the tags: `git fetch --all --tags`
5. Then, I created a new tag: `git tag 1.11.0`
6. Finally, I pushed this new tag: `git push --tags`

1. Question (❓): Did I do the above right, am I missing something obvious or doing too much?
2. Question (❓): Is it necessary for get the version catalog attached to the release ([context](https://github.com/Automattic/android-dependency-catalog/pull/10#issuecomment-1477239151))? To my understanding the dependency cache is not too necessary.
3. Suggestion (💡): What if we remove the need for creating a tag manually and publish a release just like it is done for the rest of the library repos, that is, straight via the GitHub interface? IMHO creating and publishing a tag manually can be a daunting experience since engineering just like me, aren't used to be doing that, at least due to the way it is done everywhere else. Sometimes, by creating and publishing a tag, someone might do a mistake, a typo, or something might be off with someones local tag environment, then that is pushed and creates a conflict of some kind, multiple reasons... Maybe this tag creation can become a GitHub action itself, not sure, wdyt? 🤔 

PS: Please take the above with a grain of salt, I am just raising this to get a converstation going, I am not having any strong opinions here, just want to avoid future manual mistakes and new converstations like this and [that](https://github.com/Automattic/android-dependency-catalog/pull/10#issuecomment-1477208680) popping-up again and again. 😊

**Comment by oguzkocer** [comment]
> 1. Question (❓): Did I do the above right, am I missing something obvious or doing too much?

That looks right to me. You only need, (1), (5) and (6). You can improve (6) by calling `git push origin 1.11.0` so you only push the tag you just created.

I think GitHub had an issue and didn't trigger the workflow to create the release. I deleted the remote tag and re-pushed the tag you created and the workflow has started. GitHub had partial outages lately, so maybe it's related to that 🤷‍♂️ 

> 2. Question (❓): Is it necessary for get the version catalog attached to the release (https://github.com/Automattic/android-dependency-catalog/pull/10#issuecomment-1477239151)? To my understanding the dependency cache is not too necessary.

That's correct, although dependency caching is still something I'd like to look into.

> 3. Suggestion (💡): What if we remove the need for creating a tag manually and publish a release just like it is done for the rest of the library repos, that is, straight via the GitHub interface?

That'd break having the published catalog as part of the release.

I feel like creating and pushing a git tag is one of the simplest actions a software developer can take. Having said that, if you think this is an issue, we can add tagging instructions to the documentation, so that there is no confusion about it. What do you think?

**Comment by ParaskP7** [comment]
👋 @oguzkocer and thank you for the reply and help! 🙇 

> That looks right to me. You only need, (1), (5) and (6). You can improve (6) by calling git push origin 1.11.0 so you only push the tag you just created.

Thanks! 👍 

> I think GitHub had an issue and didn't trigger the workflow to create the release. I deleted the remote tag and re-pushed the tag you created and the workflow has started. GitHub had partial outages lately, so maybe it's related to that 🤷‍♂️

Eh... 🤷 Thanks Oguz! 🙇 

> That's correct, although dependency caching is still something I'd like to look into.

👍

> That'd break having the published catalog as part of the release.

Got it! 👍 

> I feel like creating and pushing a git tag is one of the simplest actions a software developer can take.

Can't argue on that... 😅 

I just meant that although creating and pushing tags might be seemingly simple, it might create some problems like pushing the wrong tag, pushing multiple tags (`git push --tags`), etc. Also, because product developers might not be used to that, that is, versus doing via the GitHub interface, it might create extra confusion. That was my main concert.

Having said that, let's continue as is, see if others might have similar concerns in the future and maybe brainstorm on it a bit more thereafter. 🙏 

> Having said that, if you think this is an issue, we can add tagging instructions to the documentation, so that there is no confusion about it. What do you think?

Actually yes, I agree, let's do it! 💯

**Pull request merged**
