### PR TITLE
Android 13 Migration Update Robolectric

### PR DESCRIPTION
**Pull request by ravishanker**
Updates Robolectric from 4.7.3 [to 4.9.2 for Android 13 Support](https://github.com/robolectric/robolectric/releases)

To test

Use this [corresponding FlucC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2685) with updated commit-SHA for making sure unit tests pass

### CODE REVIEW

**Review by oguzkocer — APPROVED** [review]

**Comment by ravishanker** [comment]
👋 @oguzkocer - Wanted to publish a [new release 1.6.0](https://github.com/Automattic/android-dependency-catalog/releases/tag/untagged-4eb9ceb2764c0ebb7810).  However, there's [a tag 1.5.0 in draft](https://github.com/Automattic/android-dependency-catalog/releases/tag/untagged-2d5d309b4ee921f61f60).  Is it OK to publish 1.6.0 including that?  Do you like publish to 1.5.0 separately first?  🙇

**Comment by oguzkocer** [comment]
@ravishanker I published the `1.5.0` separately just now. It's probably an oversight.

Publishing a new version is a little bit different with this repo. Instead of creating a release, it's best to create the tag first and GitHub actions will create a draft release for you. This is so that the version catalog can be attached to the release. This build will also create a dependency cache for us that we can use in our CI. [Here is a guide on how to publish a new version.](https://github.com/Automattic/android-dependency-catalog#releasing-a-new-catalog-version) Let me know if you have any questions!

**Comment by ravishanker** [comment]
> @ravishanker I published the `1.5.0` separately just now. It's probably an oversight.
> 
Thank you

> Publishing a new version is a little bit different with this repo. Instead of creating a release, it's best to create the tag first and GitHub actions will create a draft release for you. This is so that the version catalog can be attached to the release. This build will also create a dependency cache for us that we can use in our CI. [Here is a guide on how to publish a new version.](https://github.com/Automattic/android-dependency-catalog#releasing-a-new-catalog-version) Let me know if you have any questions!

👋 @oguzkocer - I tried creating a tag 1.6.0 a while ago.  I don't see any draft release created by Github actions so far.  Not sure, what am I missing!

**Comment by ParaskP7** [comment]
> 👋 @oguzkocer - I tried creating a tag 1.6.0 a while ago. I don't see any draft release created by Github actions so far. Not sure, what am I missing!

Yea, I am not sure what is happening as well, I think, earlier this morning, I too saw a new `1.6.0` tag being created and I am sure I saw the new `1.6.0` draft release being created as well, just not published yet, not sure what happened thereafter as I am not seeing any of those anymore... 🤔 🤷

**Comment by oguzkocer** [comment]
@ravishanker I am sorry to ask an obvious question, but I just want to make sure we eliminate the straightforward answers first. Did you forget to push the tag to remote by any chance? I don't see the `1.6.0` tag [here](https://github.com/Automattic/android-dependency-catalog/tags).

Note that there is also no GitHub action triggered by the `1.6.0` tag. You can see the [release actions here](https://github.com/Automattic/android-dependency-catalog/actions/workflows/release.yml).

I'd be happy to create that release for you and debug any issues that might occur, but I wanted to double check with you first in case you wanted to give it another try.

**Comment by ravishanker** [comment]
@oguzkocer - Tried again and pushed the tag to remote and [can be be seen here](https://github.com/Automattic/android-dependency-catalog/tags).  However, [the build seems to be failing](https://buildkite.com/automattic/android-dependency-catalog)!

**Comment by ravishanker** [comment]
It seems to have published catalog but [failing on cache dependencies](https://buildkite.com/automattic/android-dependency-catalog/builds/97#018706ef-9231-4685-97f1-f86e8894076b)


>[2023-03-22T01:35:29Z] * What went wrong:
--
Execution failed for task ':example:processDebugAndroidTestManifest'.

>Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [androidx.security:security-crypto:1.0.0] /var/lib/buildkite-agent/.gradle/caches/transforms-3/decca9a1bcc3fbbc04f1ff97fe696176/transformed/jetified-security-crypto-1.0.0/AndroidManifest.xml as the library might be using APIs not available in 21

>Suggestion: use a compatible library with a minSdk of at most 21,or increase this project's minSdk version to at least 23, or use tools:overrideLibrary="androidx.security" to force usage (may lead to runtime failures)

Raised another [PR updating the example compileSdk and minSdk](https://github.com/Automattic/android-dependency-catalog/pull/11).  Is this PR necessary to fix the issue?

**Comment by oguzkocer** [comment]
@ravishanker Thank you for addressing the `minSdk` issue. The cache dependencies failure is not a blocker in this case, so please feel free to publish the [`1.6.0` release](https://github.com/Automattic/android-dependency-catalog/releases/tag/untagged-941f4f1088c1dd80bb08) as planned.

**Pull request merged**
